### PR TITLE
Uses Drop impl to ensure passwords are zeroed on error

### LINKED ISSUE #41: Doesn't zero password memory when terminal reset fails
In particular, see the error path [here](https://github.com/conradkleinespel/rpassword/blob/master/src/lib.rs#L120), which bails out before zeroing. I’m about to submit a PR that fixes this in a principled and robust (I think!) way.

### PR DESCRIPTION
**Pull request by tov**
This fixes #41 by wrapping the `String` that holds the password in a new type, `ZeroOnDrop`, that zeroes the string inside when it's dropped. This means that a good portion of the code for zeroing disappears, which I think makes the code a bit more readable. It should also make it harder to forget to zero it. The `ZeroOnDrop` struct provides a method `into_inner` that returns the contains `String` by value, for the case where we actually want it.

### CODE REVIEW

File: src/zero_on_drop.rs [hunk 1]
```diff
@@ -0,0 +1,69 @@
...
+        ZeroOnDrop {
+            inner: Inner(String::new())
+        }
+    }
+
+    pub fn into_inner(mut self) -> String {
+        mem::replace(&mut self.inner.0, String::new())
+    }
+
+    pub fn zero_pop(&mut self) {
```
Comment (conradkleinespel) [inline src/zero_on_drop.rs]: @tov What are you trying to do here? Could you explain line by line what you're doing, please ?

Comment (tov) [reply src/zero_on_drop.rs]: Sure. It’s an attempt to overwrite the (CR)NL with 0s when removing them, since they won’t get zeroed by the `Drop` later. I’m not sure it’s necessary, and it could certainly be done less awkwardly.

The current code avoids assuming the UTF-8 length of the popped element. Instead, it remembers the length before it pops the last char of the string. Then it pushes 0s until the remembered length is restored. Finally, it pops those 0s again. (Doing this on my phone from memory, hope it’s right.)

Comment (conradkleinespel) [reply src/zero_on_drop.rs]: Thanks for explaining that to me.

For the sake of simplicity, and because I don't think this particular thing is a security risk, I'm going to merge the PR but then remove the `zero_pop()` part and keep `pop()` as before.

I hope that's alright with you.

**Comment by conradkleinespel** [comment]
@tov Thanks again for your help ! I've added you to the README.md. I've just waiting for the builds to finish, if it's all green I'll publish as version 4.0.5 on crates.io.

File: src/zero_on_drop.rs (hunk 1 above)
Comment (tov) [reply src/zero_on_drop.rs]: It’s more than alright with me. It was pretty silly code, but I figured it was worth noticing. Thanks!
